name: Merge Databases
on:
  schedule:
    - cron: "*/10 * * * *" # Every 15 mins
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Fix Git HTTP/2 error
        run: git config --global http.version HTTP/1.1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - name: Run Merge Script
        env:
          SUPABASE_URL: ${{ secrets.DB_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.DB_SUPABASE_TOKEN }}
        run: node dashboard/scripts/merge_and_upload.js
