name: Merge Databases
on:
  schedule:
    - cron: "*/10 * * * *" # Every 15 mins
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - name: Run Merge Script
        env:
          SUPABASE_URL: ${{ secrets.DB_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.DB_SUPABASE_TOKEN }}
        run: node scripts/merge_and_upload.js
